# Generated by Django 5.2.13 on 2026-08-05 01:57

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_cnss_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CNSSRequestForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('establishment_name', models.CharField(blank=True, max_length=200)),
                ('establishment_code', models.CharField(blank=True, max_length=50)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('insured_first_name', models.CharField(blank=True, max_length=100)),
                ('insured_last_name', models.CharField(blank=True, max_length=100)),
                ('insured_cnss_number', models.CharField(blank=True, max_length=50)),
                ('insured_cin_number', models.CharField(blank=True, max_length=50)),
                ('insured_address', models.CharField(blank=True, max_length=255)),
                ('insured_affiliation_country', models.CharField(blank=True, max_length=100)),
                ('beneficiary_first_name', models.CharField(blank=True, max_length=100)),
                ('beneficiary_last_name', models.CharField(blank=True, max_length=100)),
                ('beneficiary_cin_number', models.CharField(blank=True, max_length=50)),
                ('beneficiary_date_of_birth', models.DateField(blank=True, null=True)),
                ('beneficiary_sex', models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=1)),
                ('relationship_to_insured', models.CharField(blank=True, max_length=10)),
                ('illness_nature', models.TextField(blank=True)),
                ('intervention_nature', models.TextField(blank=True)),
                ('hospitalization_nature', models.TextField(blank=True)),
                ('admission_reason', models.TextField(blank=True)),
                ('expected_admission_date', models.DateField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cnss_request', to='visits.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CNSSEstimationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=150)),
                ('is_included', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.cnssrequestform')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('UPLOADED', 'Scanné'), ('GENERATED', 'Généré automatiquement')], default='UPLOADED', max_length=20)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=documents.models.thumbnail_upload_path)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrative_documents', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visits.visit')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('blank_pdf', models.FileField(upload_to='form_templates/')),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_type', models.CharField(choices=[('CNSS_DEFAULT', 'PDF CNSS'), ('CUSTOM', 'PDF personnalisé')], max_length=20)),
                ('file', models.FileField(upload_to='generated_pdfs/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_documents', models.ManyToManyField(related_name='generated_pdfs', to='documents.document')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_pdfs', to='visits.visit')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('patient__isnull', False), ('visit__isnull', True)), models.Q(('patient__isnull', True), ('visit__isnull', False)), _connector='OR'), name='document_belongs_to_exactly_one_parent'),
        ),
    ]
