# Generated by Django 5.2.13 on 2026-08-05 20:19

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_seed_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, upload_to=documents.models.document_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=documents.models.thumbnail_upload_path),
        ),
    ]
