# Generated by Django 5.2.13 on 2026-08-07 10:15

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file_alter_document_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cnssestimationline',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cnssrequestform',
            name='total_montant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculé à partir des lignes, mais modifiable manuellement.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='generatedpdf',
            name='file',
            field=models.FileField(max_length=255, upload_to=documents.models.generated_pdf_upload_path),
        ),
        migrations.CreateModel(
            name='EstimationPhrase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_label', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=255)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('row_label', 'text')},
            },
        ),
    ]
