# Generated by Django 5.2.13 on 2026-08-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_cnssestimationline_montant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnssrequestform',
            name='dossier_hospitalisation_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cnssrequestform',
            name='hospitalization_type',
            field=models.CharField(blank=True, choices=[('MALADIE', 'Maladie'), ('ALD', 'ALD'), ('MATERNITE', 'Maternité'), ('ACCIDENT', 'Accident')], max_length=10),
        ),
        migrations.AddField(
            model_name='cnssrequestform',
            name='n_compostage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cnssrequestform',
            name='patient_inp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cnssrequestform',
            name='service_hospitalisation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cnssrequestform',
            name='urgent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
