# Generated by Django 5.2.13 on 2026-08-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_cnssrequestform_dossier_hospitalisation_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnssrequestform',
            name='hospitalization_type',
            field=models.CharField(blank=True, choices=[('MALADIE', 'Maladie'), ('ALD', 'ALD'), ('MATERNITE', 'Maternité'), ('ACCIDENT', 'Accident')], max_length=40),
        ),
        migrations.AlterField(
            model_name='cnssrequestform',
            name='relationship_to_insured',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
