# Generated by Django 5.2.13 on 2026-08-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_cnssrequestform_hospitalization_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnssrequestform',
            name='hospitalization_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
