# Generated by Django 5.2.13 on 2026-08-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_cnssrequestform_hospitalization_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisSejourLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=50)),
                ('nbr_jour', models.PositiveIntegerField(blank=True, null=True)),
                ('p_u', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_sejour_lines', to='documents.cnssrequestform')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
