# Generated by Django 5.2.13 on 2026-08-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_fraissejourline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraissejourline',
            name='p_u',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
