# Generated by Django 5.2.13 on 2026-08-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_fraissejourline_p_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnssestimationline',
            name='lettre_cle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cnssestimationline',
            name='valeur_cle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
