# Generated by Django 5.2.13 on 2026-08-16 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_cnssestimationline_lettre_cle_and_more'),
        ('patients', '0003_insuranceprovider_patient_insurance_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='insurance_provider',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour un modèle générique (CNSS par défaut).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.insuranceprovider'),
        ),
    ]
