# Generated by Django 5.2.13 on 2026-08-05 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cnss_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='N° CNSS')),
                ('cin_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='N° CIN')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('relationship_to_insured', models.CharField(choices=[('SELF', 'Assuré principal'), ('CHILD', 'Enfant'), ('SPOUSE', 'Conjoint')], default='SELF', max_length=10, verbose_name='Lien de parenté')),
                ('insured_first_name', models.CharField(blank=True, max_length=100)),
                ('insured_last_name', models.CharField(blank=True, max_length=100)),
                ('insured_cnss_number', models.CharField(blank=True, max_length=50)),
                ('insured_cin_number', models.CharField(blank=True, max_length=50)),
                ('insured_address', models.CharField(blank=True, max_length=255)),
                ('insured_affiliation_country', models.CharField(blank=True, default='Maroc', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='doctors.doctor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
